AddCSLuaFile()
MsgN("") 
MsgN("Mrpg system init")
include("_classcore/utils.lua")
include("_classcore/BehaviorGraph.lua")
include("_classcore/animation.lua")

include("_classcore/magiceffect.lua")
include("_classcore/ability.lua")
include("_classcore/abilitiespanel.lua") 
MsgN("")                   