if SERVER then
	resource.AddFile( "models/heroes/kindred/kindred.mdl" ) 
	resource.AddFile( "models/heroes/kindred/wolf.mdl" )  
	resource.AddFile( "materials/models/heroes/kindred/DefaultMaterial.vmt" ) 
	resource.AddFile( "materials/models/heroes/kindred/Kindred_Base_TX_CM.vtf" ) 
	resource.AddFile( "materials/models/heroes/kindred/Kindred_Lum.vtf" ) 
	resource.AddFile( "materials/models/heroes/kindred/wolf/DefaultMaterial.vmt" ) 
	resource.AddFile( "materials/models/heroes/kindred/wolf/KindredWolf_base_TX_CM.vtf" )
	resource.AddFile( "sound/heroes/kindred/bow.wav" )
	resource.AddFile( "sound/heroes/kindred/dance.wav" )
	resource.AddFile( "sound/heroes/kindred/jump1.wav" )
	resource.AddFile( "sound/heroes/kindred/jump2.wav" )
	resource.AddFile( "sound/heroes/kindred/jump3.wav" )
	resource.AddFile( "sound/heroes/kindred/step1.wav" )
	resource.AddFile( "sound/heroes/kindred/step2.wav" )
	resource.AddFile( "sound/heroes/kindred/step3.wav" )
	resource.AddFile( "sound/heroes/kindred/step4.wav" )
	resource.AddFile( "sound/heroes/kindred/wolfcast1.wav" )
	resource.AddFile( "sound/heroes/kindred/wolfcast2.wav" )
	resource.AddFile( "sound/heroes/kindred/wolfcast3.wav" )
	MsgN("rad_auto") 
end